#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Number-Compare
Version  : 0.03
Release  : 25
URL      : https://cpan.metacpan.org/authors/id/R/RC/RCLAMP/Number-Compare-0.03.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RC/RCLAMP/Number-Compare-0.03.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libn/libnumber-compare-perl/libnumber-compare-perl_0.03-1.debian.tar.gz
Summary  : ~
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Number-Compare-license = %{version}-%{release}
Requires: perl-Number-Compare-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the perl-Number-Compare package.
Group: Development
Provides: perl-Number-Compare-devel = %{version}-%{release}
Requires: perl-Number-Compare = %{version}-%{release}

%description dev
dev components for the perl-Number-Compare package.


%package license
Summary: license components for the perl-Number-Compare package.
Group: Default

%description license
license components for the perl-Number-Compare package.


%package perl
Summary: perl components for the perl-Number-Compare package.
Group: Default
Requires: perl-Number-Compare = %{version}-%{release}

%description perl
perl components for the perl-Number-Compare package.


%prep
%setup -q -n Number-Compare-0.03
cd %{_builddir}
tar xf %{_sourcedir}/libnumber-compare-perl_0.03-1.debian.tar.gz
cd %{_builddir}/Number-Compare-0.03
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Number-Compare-0.03/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Number-Compare
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Number-Compare/60a054add6d5dbf8dbb44b22628755503b09e08c || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Number::Compare.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Number-Compare/60a054add6d5dbf8dbb44b22628755503b09e08c

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
